In [1]:
import xgboost
print("XGBoost is installed successfully!")

XGBoost is installed successfully!

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler

In [3]:
df = pd.read_csv("creditcard_sample.csv")

In [4]:
df

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,-0.843892,0.035464,6.015788,-0.263557,-5.232175,1.012054,1.409333,6.615803,-0.532625,2.145713,...,-0.361494,-2.890211,-0.855108,2.394570,-1.918921,-4.120211,-5.433612,6.713389,2.852118,0
1,0.046244,-0.929981,-5.016888,-1.463347,-1.939124,-1.676509,0.442727,-0.142975,-0.651400,2.014431,...,1.291772,0.926365,-0.717916,1.689361,3.070980,-6.459974,-0.069959,-3.421292,2.451963,0
2,0.743019,2.266748,-0.646696,-0.270072,5.348949,-1.120282,0.954233,-0.615076,-1.120524,-0.203716,...,1.584151,-0.785146,-1.419477,2.001424,2.537186,2.364429,1.060417,0.097379,-0.781580,0
3,-0.546052,1.844008,-4.301339,-1.024388,-0.652781,-2.950979,0.052936,3.636302,-0.511703,2.302043,...,0.001468,1.702899,0.492796,1.712970,6.695562,-14.211853,-1.317618,-3.267106,0.882769,0
4,0.299020,1.193579,-2.878079,-0.378966,5.781787,0.195662,0.212282,-0.788509,0.670138,4.100414,...,1.029566,3.483952,0.797696,-0.124187,5.604371,-1.074748,0.819075,-2.443539,-2.337409,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,0.698060,2.510245,-2.784876,0.461767,-0.822478,-2.068672,-0.373091,-2.324460,-0.812126,1.255050,...,0.917295,1.546812,-0.851475,-1.006565,2.685889,-4.701061,-0.770998,-1.215973,-0.677760,0
4996,2.073756,-0.475224,-3.631901,0.217770,0.747656,-0.755620,-0.780997,-4.734237,1.022725,-0.168307,...,0.277164,2.142629,0.300356,0.502784,0.345629,-0.263717,2.305516,-3.027955,-2.582447,0
4997,0.034163,-6.232224,-8.921416,0.798428,6.469958,-1.614794,-0.706853,-10.028058,1.175088,1.882480,...,3.539672,1.593992,-0.866075,-0.310765,6.133968,0.531947,5.837198,-6.944631,-2.538723,0
4998,-0.091683,-0.915946,0.569174,-0.423498,-4.799030,-1.062203,-0.708375,1.988281,-0.072223,3.667553,...,0.678070,-0.649856,0.616976,2.972210,1.624760,-7.600729,-2.920293,1.911550,1.140166,0
4999,0.795748,-3.468613,0.709786,0.954872,7.434671,0.472061,-1.011711,1.798903,0.094934,3.272681,...,1.629271,-1.638937,0.427858,0.892259,1.978409,3.942016,2.295519,1.298157,-3.381028,0

In [5]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,-0.843892,0.035464,6.015788,-0.263557,-5.232175,1.012054,1.409333,6.615803,-0.532625,2.145713,...,-0.361494,-2.890211,-0.855108,2.394570,-1.918921,-4.120211,-5.433612,6.713389,2.852118,0
1,0.046244,-0.929981,-5.016888,-1.463347,-1.939124,-1.676509,0.442727,-0.142975,-0.651400,2.014431,...,1.291772,0.926365,-0.717916,1.689361,3.070980,-6.459974,-0.069959,-3.421292,2.451963,0
2,0.743019,2.266748,-0.646696,-0.270072,5.348949,-1.120282,0.954233,-0.615076,-1.120524,-0.203716,...,1.584151,-0.785146,-1.419477,2.001424,2.537186,2.364429,1.060417,0.097379,-0.781580,0
3,-0.546052,1.844008,-4.301339,-1.024388,-0.652781,-2.950979,0.052936,3.636302,-0.511703,2.302043,...,0.001468,1.702899,0.492796,1.712970,6.695562,-14.211853,-1.317618,-3.267106,0.882769,0
4,0.299020,1.193579,-2.878079,-0.378966,5.781787,0.195662,0.212282,-0.788509,0.670138,4.100414,...,1.029566,3.483952,0.797696,-0.124187,5.604371,-1.074748,0.819075,-2.443539,-2.337409,0

In [6]:
df.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,...,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,-0.015974,-1.351683,-2.668952,-0.001327,1.495974,-0.980260,0.004728,-2.688328,-0.007117,1.544335,...,1.012581,0.949579,0.006799,-0.004724,3.645560,-3.122242,0.953176,-2.003639,-1.054420,0.010000
std,0.996517,3.950294,3.609540,0.991530,4.075179,1.782201,1.005067,4.302148,1.002520,2.747001,...,1.924267,1.739101,0.999333,0.998167,3.129933,4.289875,2.155724,2.919118,2.081651,0.099509
min,-3.532532,-15.550493,-15.264016,-3.713341,-13.885934,-6.874450,-3.515383,-17.644120,-3.914706,-8.019431,...,-5.292481,-5.202145,-3.480141,-3.411111,-6.376844,-17.333908,-6.030565,-11.730251,-8.517722,0.000000
25%,-0.686246,-3.909443,-5.047845,-0.657230,-1.309608,-2.156936,-0.668006,-5.600163,-0.687768,-0.328864,...,-0.284320,-0.232050,-0.658239,-0.677722,1.566843,-5.999901,-0.543079,-3.964978,-2.437816,0.000000
50%,-0.007172,-1.361419,-2.615467,0.009508,1.454558,-0.999160,0.016365,-2.730220,0.001229,1.581724,...,1.009712,0.947821,0.018345,-0.017330,3.641766,-3.155481,0.971285,-2.001227,-1.032860,0.000000
75%,0.652283,1.312037,-0.249276,0.678612,4.257018,0.211325,0.668913,0.172246,0.671505,3.385756,...,2.324811,2.139893,0.685782,0.680950,5.711908,-0.304903,2.449730,-0.049590,0.338054,0.000000
max,3.591999,14.187354,10.805966,3.276796,16.062819,5.979216,3.856630,15.374638,3.789975,12.124327,...,8.287584,7.920980,4.100342,3.716209,14.702941,13.819245,8.392255,10.054001,6.575000,1.000000

In [8]:
df.dtypes

Time      float64
V1        float64
V2        float64
V3        float64
V4        float64
V5        float64
V6        float64
V7        float64
V8        float64
V9        float64
V10       float64
V11       float64
V12       float64
V13       float64
V14       float64
V15       float64
V16       float64
V17       float64
V18       float64
V19       float64
V20       float64
V21       float64
V22       float64
V23       float64
V24       float64
V25       float64
V26       float64
V27       float64
V28       float64
Amount    float64
Class       int64
dtype: object

In [9]:
# Check for imbalance
print("Class distribution:\n", df['Class'].value_counts())

Class distribution:
 Class
0    4950
1      50
Name: count, dtype: int64

In [10]:
# Features and target
X = df.drop('Class', axis=1)
y = df['Class']

In [11]:
# Normalize features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Train/test split (80/20)
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42, stratify=y)

In [12]:
# XGBoost Classifier
model = XGBClassifier(use_label_encoder=False, eval_metric='logloss')
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)

# Evaluation
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

C:\ProgramData\anaconda3\Lib\site-packages\xgboost\training.py:183: UserWarning: [20:00:39] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

Confusion Matrix:
 [[990   0]
 [  8   2]]

Classification Report:
               precision    recall  f1-score   support

           0       0.99      1.00      1.00       990
           1       1.00      0.20      0.33        10

    accuracy                           0.99      1000
   macro avg       1.00      0.60      0.66      1000
weighted avg       0.99      0.99      0.99      1000

In [14]:
predictions = model.predict(X_test)

# Convert 0/1 to "No"/"Yes"
output = ["Yes" if pred == 1 else "No" for pred in predictions]

# Show results with transaction indices
results_df = pd.DataFrame({"Transaction Index": X_test.argmax(axis=1), "Fraud": output})
print(results_df.head(20))  # Show top 20 predictions

    Transaction Index Fraud
0                  11    No
1                  27    No
2                  24    No
3                  29    No
4                  16    No
5                   9    No
6                  26    No
7                   6    No
8                  26    No
9                  12    No
10                 28    No
11                 17    No
12                  0    No
13                  3    No
14                 17    No
15                 29    No
16                  0    No
17                 10    No
18                 10    No
19                  8    No